AutomatedTellerMachine/Controllers/GameInfoesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;


namespace AutomatedTellerMachine.Controllers
{

    public class GameInfoesController : Controller
    {
        //private GameInfoDbContext db = new GameInfoDbContext();
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: GameInfoes
        public ActionResult Index()
        {
            return View(db.GamesInfos.ToList());
        }

        public ActionResult GameCatalogTemp()
        {
            return View(db.GamesInfos.ToList());
        }

        // GET: GameInfoes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameInfo gameInfo = db.GamesInfos.Find(id);
            if (gameInfo == null)
            {
                return HttpNotFound();
            }
            return View(gameInfo);
        }

        [Authorize(Roles = "Admin")]
        // GET: GameInfoes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GameInfoes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Developer,Publisher,Platforms,ReleaseDate,Genre,MetaCriticScore,Description,InPageImage,Thumbnail,Thumbnail2,Thumbnail3,Thumbnail4,VideoUrl,VideoUrl2,ReviewLinks,ReviewLinks2,ReviewLinks3,ReviewLinks4")] GameInfo gameInfo)
        {
            if (ModelState.IsValid)
            {
                db.GamesInfos.Add(gameInfo);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(gameInfo);
        }
        [Authorize(Roles = "Admin")]
        // GET: GameInfoes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameInfo gameInfo = db.GamesInfos.Find(id);
            if (gameInfo == null)
            {
                return HttpNotFound();
            }
            return View(gameInfo);
        }

        // POST: GameInfoes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Developer,Publisher,Platforms,ReleaseDate,Genre,MetaCriticScore,Description,InPageImage,Thumbnail,Thumbnail2,Thumbnail3,Thumbnail4,VideoUrl,VideoUrl2,ReviewLinks,ReviewLinks2,ReviewLinks3,ReviewLinks4")] GameInfo gameInfo)
        {
            if (ModelState.IsValid)
            {
                db.Entry(gameInfo).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(gameInfo);
        }
        [Authorize(Roles = "Admin")]
        // GET: GameInfoes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            GameInfo gameInfo = db.GamesInfos.Find(id);
            if (gameInfo == null)
            {
                return HttpNotFound();
            }
            return View(gameInfo);
        }
        [Authorize(Roles = "Admin")]
        // POST: GameInfoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            GameInfo gameInfo = db.GamesInfos.Find(id);
            db.GamesInfos.Remove(gameInfo);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomatedTellerMachine/Views/GameInfoes/Create.cshtml
@model AutomatedTellerMachine.Models.GameInfo

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>GameInfo</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Developer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Developer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Developer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Publisher, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Publisher, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Publisher, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Platforms, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Platforms, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Platforms, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReleaseDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReleaseDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReleaseDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Genre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Genre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MetaCriticScore, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MetaCriticScore, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MetaCriticScore, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InPageImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InPageImage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InPageImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thumbnail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thumbnail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thumbnail2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thumbnail2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thumbnail3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thumbnail3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Thumbnail4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Thumbnail4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Thumbnail4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoUrl, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoUrl, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoUrl, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VideoUrl2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.VideoUrl2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.VideoUrl2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewLinks, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewLinks, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewLinks, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewLinks2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewLinks2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewLinks2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewLinks3, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewLinks3, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewLinks3, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReviewLinks4, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReviewLinks4, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReviewLinks4, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

AutomatedTellerMachine/Views/GameInfoes/Delete.cshtml
@model AutomatedTellerMachine.Models.GameInfo

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GameInfo</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Developer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Developer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Publisher)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Publisher)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Platforms)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Platforms)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReleaseDate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReleaseDate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MetaCriticScore)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MetaCriticScore)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InPageImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InPageImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Thumbnail4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Thumbnail4)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VideoUrl2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VideoUrl2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewLinks)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewLinks)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewLinks2)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewLinks2)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewLinks3)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewLinks3)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReviewLinks4)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReviewLinks4)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AutomatedTellerMachine/Views/GameInfoes/Details.cshtml
@model AutomatedTellerMachine.Models.GameInfo

@{
    ViewBag.Title = "Details";
}

<div class="container">

    <div class=" container panel panel-primary col-xs-3" style="height: 350px;">
        <div class="panel-heading">
            <h3 class="panel-title">Game Overview</h3>
        </div>
        <div class="panel-body ">
            Title: @Html.DisplayFor(model => model.Title)<br>
            Developer: @Html.DisplayFor(model => model.Developer)<br>
            Publisher: @Html.DisplayFor(model => model.Publisher)<br>
            Platform(s): @Html.DisplayFor(model => model.Platforms)<br>
            Release Date: @Html.DisplayFor(model => model.ReleaseDate)<br>
            Metacritic: @Html.DisplayFor(model => model.MetaCriticScore)<br>
            Genre: @Html.DisplayFor(model => model.Genre)<br>
        </div>
    </div>

    <div class=" container col-xs-6 well well-lg" style="height: 350px;">
        @Html.DisplayFor(model => model.Description)
    </div>

    <div class="container col-xs-2">
        <a href="http://blog.dota2.com/?l=english"><img class="img-rounded" src="@Html.DisplayFor(model => model.InPageImage)" alt="Dota 2"></a>
    </div>

</div>

<div class="container imageSetting">
    <div class="panel panel-default text-center" data-toggle="collapse" data-target="#demo">

        <div id="menu_toggle" class="panel-body text-center">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            Reviews <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </div>

        <div id="demo" class="collapse">

            <div class="col-xs-3 imageSetting">
                <a href="@Html.DisplayFor(model => model.ReviewLinks)" class="thumbnail">
                    <img class=" img-rounded" src="/Images/ReviewThumbs/ignReviewThumb255.png" alt="IGNReviewThumb">
                </a>
            </div>

            <div class="col-xs-3 imageSetting">
                <a href="@Html.DisplayFor(model => model.ReviewLinks2)" class="thumbnail">
                    <img class=" img-rounded" src="/Images/ReviewThumbs/kotaku_review255.png" alt="kotakureview">
                </a>
            </div>

            <div class="col-xs-3 imageSetting">
                <a href="@Html.DisplayFor(model => model.ReviewLinks3)" class="thumbnail">
                    <img class=" img-rounded" src="/Images/ReviewThumbs/gamespotReviewThumb255.png" alt="GamespotReviewThumb">
                </a>
            </div>

            <div class="col-xs-3 imageSetting">
                <a href="@Html.DisplayFor(model => model.ReviewLinks4)" class="thumbnail">
                    <img class=" img-rounded" src="/Images/ReviewThumbs/eurogamerReviewThumb255.png" alt="EurogamerReviewThumb">
                </a>
            </div>
            <div class="clearfix">
            </div>
        </div>
    </div>
</div>

<div class="container imageSetting">
    <div class="panel panel-default text-center" data-toggle="collapse" data-target="#demo2">
        <div id="menu_toggle2" class="panel-body text-center">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Trailers <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </div>

        <div id="demo2" class="collapse">

            <iframe width="552" height="315" src="@Html.DisplayFor(model => model.VideoUrl)" frameborder="0" allowfullscreen></iframe>
            <iframe width="552" height="315" src="@Html.DisplayFor(model => model.VideoUrl2)" frameborder="0" allowfullscreen></iframe>

        </div>
    </div>
</div>


<div class="container imageSetting">
    <div class="panel panel-default text-center" data-toggle="collapse" data-target="#demo3">
        <div id="menu_toggle3" class="panel-body text-center">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Screenshots <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
        </div>
        <div id="demo3" class="collapse">

            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <a href="@Html.DisplayFor(model => model.Thumbnail)" class="thumbnail">
                        <img src="@Html.DisplayFor(model => model.Thumbnail)" alt="Dota2Screenshot1">
                    </a>
                </div>

                <div class="col-xs-6 col-md-3">
                    <a href="@Html.DisplayFor(model => model.Thumbnail2)" class="thumbnail">
                        <img src="@Html.DisplayFor(model => model.Thumbnail2)" alt="Dota2Screenshot2">
                    </a>
                </div>

                <div class="col-xs-6 col-md-3">
                    <a href="@Html.DisplayFor(model => model.Thumbnail3)" class="thumbnail">
                        <img src="@Html.DisplayFor(model => model.Thumbnail3)" alt="Dota2Screenshot3">
                    </a>
                </div>

                <div class="col-xs-6 col-md-3">
                    <a href="@Html.DisplayFor(model => model.Thumbnail4)" class="thumbnail">
                        <img src="@Html.DisplayFor(model => model.Thumbnail4)" alt="Dota2Screenshot3">
                    </a>
                </div>

            </div>
        </div>
    </div>
</div>
<div class="clearfix">

</div>

@section Scripts
 {
    <script type="text/javascript">
        $('#menu_toggle').click(function () {
            $(this).find('span').toggleClass('glyphicon glyphicon-plus-sign').toggleClass('glyphicon glyphicon-minus-sign');
        });
        $('#menu_toggle2').click(function () {
            $(this).find('span').toggleClass('glyphicon glyphicon-plus-sign').toggleClass('glyphicon glyphicon-minus-sign');
        });
        $('#menu_toggle3').click(function () {
            $(this).find('span').toggleClass('glyphicon glyphicon-plus-sign').toggleClass('glyphicon glyphicon-minus-sign');
        });
    </script>
}

AutomatedTellerMachine/Views/GameInfoes/GameCatalogTemp.cshtml
@using System.Linq
@using AutomatedTellerMachine.Models
@using Newtonsoft.Json
@model System.Collections.Generic.IEnumerable<AutomatedTellerMachine.Models.GameInfo>
@{
    ViewBag.Title = "GameCatalogTemp";
}
@*
    @foreach (var item in Model.Reverse())
    {
        <div class="col-xs-3 catpad">
            <a href='@Url.Action("Details", "GameInfoes", new {id = item.Id})'><img class="img-rounded img-responsive" src="@Html.DisplayFor(modelItem => item.InPageImage)" alt="@Html.DisplayFor(modelItem => item.Title)"></a>
        </div>
    }
*@

<div data-bind="foreach:currentArticles">
    <div class="col-xs-3 catpad">
        <a data-bind="attr: { 'href': '@Url.Action("Details", "GameInfoes")/' + Id}">
            <img class="img-rounded img-responsive" data-bind="attr:{src: InPageImage}" alt="text:title">
        </a>
    </div>
</div>
<div class="col-xs-12">
    <span data-bind="click:previousPage,visible:currentPage() > 1" class="glyphicon glyphicon-circle-arrow-left" style="cursor:pointer;"></span>
    <span data-bind="text:currentPage"></span>
    <span data-bind="click:nextPage,visible:currentPage() < lastPage" class="glyphicon glyphicon-circle-arrow-right" style="cursor:pointer;"></span>
</div>
<div class="col-xs-12">
    <span> </span>
</div>

<div class="col-xs-12">
    <span> </span>
</div>

@if (User.IsInRole("Admin"))
{
    <div class="col-xs-12">
        <a href='@Url.Action("Index", "GameInfoes")' class="glyphicon glyphicon-plus" title="Manage Review entries"></a>
    </div>
}
<div class="clearfix"></div>

<script src="~/Scripts/knockout-3.3.0.js"></script>
<script>

    function NewsViewModel() {
        var self = this;

        // properties
        self.articles = @Html.Raw(JsonConvert.SerializeObject(Model, new JsonSerializerSettings{ReferenceLoopHandling = ReferenceLoopHandling.Ignore}));
        self.pageSize = 8;
        self.lastPage = Math.ceil(self.articles.length / self.pageSize);
        self.currentPage = ko.observable(1);
        self.currentArticles = ko.computed(function(){
            var startIndex = (self.currentPage() - 1) * self.pageSize;
            var endIndex = startIndex + self.pageSize;
           // var reversed = self.articles.reverse();
            self.articles.sort(function(left, right) 
            { return left.Title === right.Title ? 0 : (left.Title < right.Title ? -1 : 1) }
            );
            return self.articles.slice(startIndex,endIndex);
        });

        // methods
        self.nextPage = function(){
            self.currentPage(self.currentPage() + 1);
        };
        self.previousPage = function(){
            self.currentPage(self.currentPage() - 1);
        };
    };

    ko.applyBindings(new NewsViewModel());
</script>