AutomatedTellerMachine/Models/CommentModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace AutomatedTellerMachine.Models
{
    public class CommentModel
    {
        public int Id { get; set; }

        public string message { get; set; }

        
        public int ForumModelId { get; set; }

        [ForeignKey("ForumModelId")]
        public virtual ForumModel ForumModel { get; set; }

        public virtual ApplicationUser User { get; set; }

        [Required]
        public string ApplicationUserId { get; set; }
    }
}

AutomatedTellerMachine/Controllers/CommentModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;

namespace AutomatedTellerMachine.Controllers
{
    public class CommentModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private int currentForumId;
        // GET: CommentModels
        public ActionResult Index(int id)
        {
            currentForumId = id;
            ViewBag.Title = db.ForumModels.Find(id).Title;
            ViewBag.Question = db.ForumModels.Find(id).Question;
            ViewBag.Sender = db.Users.Find(db.ForumModels.Find(id).ApplicationUserId).UserName;
            ViewBag.ThreadId = id;
            ViewBag.AppUserId = User.Identity.GetUserId();
            var commentModels = db.CommentModels.Where(c => c.ForumModelId == id);
            return View(commentModels.ToList());
        }
        [Authorize]
        [HttpPost]
        public ActionResult Index(string message, string threadId)
        {
            var commentModel = new CommentModel();
            commentModel.ForumModelId = Int32.Parse(threadId);
            commentModel.Id = db.CommentModels.Count() + 1;
            commentModel.ApplicationUserId = User.Identity.GetUserId();
            commentModel.message = message;
            
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                db.CommentModels.Add(commentModel);
                db.SaveChanges();

                var ComModel = db.CommentModels.Where(c => c.ForumModelId.ToString() == threadId);
                return Index(Int32.Parse(threadId));
            }
            var commentModels = db.CommentModels.Where(c => c.ForumModelId == commentModel.ForumModelId);
            return View(commentModels.ToList());
        }
        

        // GET: CommentModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CommentModel commentModel = db.CommentModels.Find(id);
            if (commentModel == null)
            {
                return HttpNotFound();
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", commentModel.ApplicationUserId);
            return View(commentModel);
        }

        // POST: CommentModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(CommentModel commentModel)
        {
            ModelState.Clear();
            if (ModelState.IsValid)
            {
                db.Entry(commentModel).State = EntityState.Modified;
                db.SaveChanges();
                
                return RedirectToAction("Index", new { id = commentModel.ForumModelId});
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", commentModel.ApplicationUserId);
            return View(commentModel);
        }

        // GET: CommentModels/Delete/5
        public ActionResult Delete(int id,string threadId)
        { 
            CommentModel commentModel = db.CommentModels.Find(id);
            try
            {
                db.CommentModels.Remove(commentModel);
                db.SaveChanges();
               return RedirectToAction("Index", new { id = Int32.Parse(threadId)});
            }
            catch
            {
            }
            return View();
        }

        // POST: CommentModels/Delete/5
       
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomatedTellerMachine/Controllers/ForumModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity;

namespace AutomatedTellerMachine.Controllers
{
    public class ForumModelsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: ForumModels
        public ActionResult Index()
        {
            var forumModels = db.ForumModels.Include(f => f.User);
            ViewBag.AppUserId = User.Identity.GetUserId();
            return View(forumModels.ToList());
        }

        [Authorize]
        // GET: ForumModels/Create
        public ActionResult Create()
        {
            ViewBag.ApplicationUserId = User.Identity.GetUserId();
            return View();
        }


        [Authorize]
        // POST: ForumModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ApplicationUserId,Title,Question")] ForumModel forumModel)
        {
            ModelState.Clear();
            forumModel.ApplicationUserId = User.Identity.GetUserId();
            forumModel.Id = db.ForumModels.Count() + 1;
            forumModel.User =
                db.CheckingAccounts.Where(x => x.ApplicationUserId == forumModel.ApplicationUserId).First().User;
            
            if (ModelState.IsValid)
            {
                db.ForumModels.Add(forumModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", forumModel.ApplicationUserId);
            return View(forumModel);
        }


        [Authorize]
        // GET: ForumModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
           
            ForumModel forumModel = db.ForumModels.Find(id);
            if (forumModel == null)
            {
                return HttpNotFound();
            }
            return View(forumModel);
        }


        [Authorize]
        // POST: ForumModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ApplicationUserId,Title,Question")] ForumModel forumModel)
        {
            ModelState.Clear();
            forumModel.ApplicationUserId = User.Identity.GetUserId();
           
            if (ModelState.IsValid)
            {
                db.Entry(forumModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ApplicationUserId = new SelectList(db.Users, "Id", "Pin", forumModel.ApplicationUserId);
            return View(forumModel);
        }


        [Authorize]
        // GET: ForumModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ForumModel forumModel = db.ForumModels.Find(id);
            if (forumModel == null)
            {
                return HttpNotFound();
            }
            return View(forumModel);
        }

        [Authorize]
        // POST: ForumModels/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
             ForumModel forumModel = db.ForumModels.Find(id);

             foreach (var item in db.CommentModels)
             {
                 CommentModel cm = db.CommentModels.Find(item.Id);

                if (cm.ForumModelId == forumModel.Id)
                {
                    db.CommentModels.Remove(cm);
                }
            }

            db.ForumModels.Remove(forumModel);
            db.SaveChanges();
            
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomatedTellerMachine/Views/CommentModels/Create.cshtml
@model AutomatedTellerMachine.Models.CommentModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CommentModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new {htmlAttributes = new {@class = "form-control"}})
                @Html.ValidationMessageFor(model => model.message, "", new {@class = "text-danger"})
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutomatedTellerMachine/Views/CommentModels/Delete.cshtml
@model AutomatedTellerMachine.Models.CommentModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>CommentModel</h4>
    <hr />
    <dl class="dl-horizontal">

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>
       
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

AutomatedTellerMachine/Views/CommentModels/Details.cshtml
@model AutomatedTellerMachine.Models.CommentModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>CommentModel</h4>
    <hr />
    <dl class="dl-horizontal">
       

        <dt>
            @Html.DisplayNameFor(model => model.message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.message)
        </dd>
        
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

AutomatedTellerMachine/Views/CommentModels/Edit.cshtml
@model AutomatedTellerMachine.Models.CommentModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ForumModelId)
    @Html.HiddenFor(model => model.User)
    @Html.HiddenFor(model => model.ApplicationUserId)
    <div class="form-horizontal">
        <h4>CommentModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.message, new { htmlAttributes = new { @class = "form-control", name="message"} })
                @Html.ValidationMessageFor(model => model.message, "", new { @class = "text-danger" })
            </div>
        </div>

        
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit"  class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

AutomatedTellerMachine/Views/CommentModels/Index.cshtml
@model System.Collections.Generic.IEnumerable<AutomatedTellerMachine.Models.CommentModel>

<h1>Topic: @ViewBag.Title</h1>
<h2>Question: @ViewBag.Question</h2>
<h4>Sender: @ViewBag.Sender</h4>



<div>
    <p>
        
    </p>
</div>
<table class="table">
    <tr>
        <th>
            Username
        </th>
        <th>
           Message
        </th>
       
        <th></th>
    </tr>
    @{ var threadid = ViewBag.ThreadId;
    }
@foreach (var item in Model) {
    <tr>
        <td>
          @Html.DisplayFor(model => item.User.UserName)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.message)
        </td>

        @if (item.ApplicationUserId.ToString() == @ViewBag.AppUserId)
        {
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id, threadId = threadid })
            </td>
        }
        else
        {
            <td></td>}
        
    </tr>
}

</table>

@if (User.Identity.IsAuthenticated)
{
    using (Html.BeginForm("Index", "CommentModels", FormMethod.Post))
    {

        <div id="formSection">
            <h3>Share your opinion below:</h3>

            <textarea name="message"></textarea>
            <input type="submit" value="Send"/>
            <input type="hidden" name="threadId" value="@ViewBag.ThreadId"/>
        </div>
    }
}
else
{
    <h4>You need to be logged in to comment on this thead</h4>
}

<div></div>

<a class="glyphicon glyphicon-arrow-left"  href='@Url.Action("Index", "ForumModels" )'></a>