AutomatedTellerMachine/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using AutomatedTellerMachine.Models;
using Microsoft.AspNet.Identity.Owin;
using System.Net.Mail;

namespace AutomatedTellerMachine.Controllers
{
    public class HomeController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET /home/index        
        
        public ActionResult Index()
        {
            /*var userId = User.Identity.GetUserId();
            var checkingAccountId = db.CheckingAccounts.Where(c => c.ApplicationUserId == userId).First().Id;
            ViewBag.CheckingAccountId = checkingAccountId;
            
            var manager = HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            var user = manager.FindById(userId);
            ViewBag.Pin = user.Pin;*/
            return View(db.NewsModels.ToList());
        }

        // GET /home/about        
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }
                
        public ActionResult Contact()
        {
            ViewBag.TheMessage = "Having trouble? Send us a message.";            

            return View();
        }

        [HttpPost]
        public ActionResult Contact(string message)
        {
            // TODO: send the message to HQ
            ViewBag.TheMessage = "Thanks, we got your message!";
            var fromAddress = new MailAddress("diokaroka@gmail.com");
            var fromPassword = "diokaroka0579123";
            var toAddress = new MailAddress("throwaway8123@gmail.com");

            string subject ="contact form";
            string body = message;

            System.Net.Mail.SmtpClient smtp = new System.Net.Mail.SmtpClient
            {
                Host = "smtp.gmail.com",
                Port = 587,
                EnableSsl = true,
                DeliveryMethod = System.Net.Mail.SmtpDeliveryMethod.Network,
                UseDefaultCredentials = false,
                Credentials = new NetworkCredential(fromAddress.Address, fromPassword)

            };

            using (var message2 = new MailMessage(fromAddress, toAddress)
            {
                Subject = subject,
                Body = body
            })


                smtp.Send(message2);
            return PartialView("_ContactThanks");
        }

        public ActionResult Foo()
        {            
            return View("About");
        }
    }
}

AutomatedTellerMachine/Controllers/NewsModelsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutomatedTellerMachine.Models;


namespace AutomatedTellerMachine.Controllers
{
    public class NewsModelsController : Controller
    {
       // private GameInfoDbContext db = new GameInfoDbContext();
        private ApplicationDbContext db = new ApplicationDbContext();
        [Authorize(Roles = "Admin")]
        // GET: NewsModels
        public ActionResult Index()
        {
            return View(db.NewsModels.ToList());
        }

        
        public ActionResult NewsPageTemp()
        {
            return View(db.NewsModels.ToList());
        }
        
        // GET: NewsModels/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.NewsModels.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

         [Authorize(Roles = "Admin")]
        // GET: NewsModels/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NewsModels/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
       [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,NewsTitle,NewsImageUrl,NewsPart1,VideoUrl,NewsPart2,Author")] NewsModel newsModel)
        {
            if (ModelState.IsValid)
            {
                db.NewsModels.Add(newsModel);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(newsModel);
        }
        [Authorize(Roles = "Admin")]
        // GET: NewsModels/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.NewsModels.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

        // POST: NewsModels/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
       [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,NewsTitle,NewsImageUrl,NewsPart1,VideoUrl,NewsPart2,Author")] NewsModel newsModel)
        {
            if (ModelState.IsValid)
            {
                db.Entry(newsModel).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(newsModel);
        }
        [Authorize(Roles = "Admin")]
        // GET: NewsModels/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NewsModel newsModel = db.NewsModels.Find(id);
            if (newsModel == null)
            {
                return HttpNotFound();
            }
            return View(newsModel);
        }

        // POST: NewsModels/Delete/5
       [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            NewsModel newsModel = db.NewsModels.Find(id);
            db.NewsModels.Remove(newsModel);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

AutomatedTellerMachine/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

AutomatedTellerMachine/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

<div id="formSection">
    <h3>Want to tell us something? Send us a Message :)</h3>
    @using (Ajax.BeginForm(new AjaxOptions
    {
        HttpMethod = "post",
        InsertionMode = InsertionMode.Replace, UpdateTargetId = "formSection"
    }))
    {
        <Textarea name="message"></Textarea>
        <input type="submit" value="Send"/>
    }
</div>
@section scripts
{
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script> 
}

AutomatedTellerMachine/Views/Home/Index.cshtml
@using System.Linq
@using Microsoft.Ajax.Utilities
@model System.Collections.Generic.IEnumerable<AutomatedTellerMachine.Models.NewsModel>
@{
    ViewBag.Title = "Home Page";
}

<div>
<div id="myCarousel" class="carousel slide" style="width: 1000px; margin: 0 auto">
    <div class="carousel-inner">
        <div class="item">
            <a href="#">
                <img src="../../Images/Carousel/oriandblind.jpg"
                     alt="Ori and the Blind Forest">
            </a>
            <div class="carousel-caption">
                <h4>Ori and The Blind Forest Review</h4>
                <p>
                    A charming and visually beautiful adventure.
                </p>
            </div>
        </div>

        <div class="item">
            <a href="#">
                <img src="../../Images/Carousel/FF-Type-0-HD_01.jpg"
                     alt="Final Fantasy Type-0 HD">
            </a>
            <div class="carousel-caption">
                <h4>Final Fantasy Type-0 HD Review</h4>
                <p>
                    A mixed rpg and in 520p no less.
                </p>
            </div>
        </div>

        <div class="item active">
            <a href="#">
                <img src="../../Images/Carousel/Bloodborne.jpg"
                     alt="BloodBorne">
            </a>
            <div class="carousel-caption">
                <h4>Third Thumbnail label</h4>
                <p>
                    Demons Souls for the PS4
                </p>
            </div>
        </div>

    </div> <a class="left carousel-control" href="#myCarousel" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    </a>

    <a class="right carousel-control" href="#myCarousel" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    </a>

</div>
    </div>

<div class="container">
    <img class="img-responsive catpad col-xs-12" src="/Images/General/Latest News.png" alt="latestnews">
    <div class="row">
    </div>
</div>

@{ var i = 0; }

@foreach (var item in Model.Reverse())
{
    i++;
    <div class="col-sm-6 col-md-6 catpad">
        <div class="img-thumbnail">
            <a href='@Url.Action("Details", "NewsModels", new {id = item.Id})'>
                <img class="img-responsive" src="@Html.DisplayFor(model => item.NewsImageUrl)" alt="@Html.DisplayFor(model => item.NewsTitle)">
                <h2 class="text-center"><span>"@Html.DisplayFor(model => item.NewsTitle)"</span></h2>
            </a>
        </div>
    </div>
    if (i > 3)
    {
        break;
    }
}
    <div class="clearfix"></div>
 

AutomatedTellerMachine/Views/Home/_ContactThanks.cshtml
<h3>@ViewBag.TheMessage</h3>